[package]
name = "zenu-cublas-sys"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for cuBLAS"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lints]
workspace = true
