[package]
name = "ruml-matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cblas = "0.4.0"
openblas-src = { version = "0.10.8", features = ["system", "cblas"] }
