name: CI

on:
  pull_request:
  push: 
    branches:
      - main

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run clippy on zenu-matrix
        run: cd zenu-matrix && cargo clippy --verbose

      - name: Run clippy on zenu-autograd
        run: cd zenu-autograd && cargo clippy --verbose

      - name: Run clippy on zenu-layer
        run: cd zenu-layer && cargo clippy --verbose

      - name: Run clippy on zenu-optimizer
        run: cd zenu-optimizer && cargo clippy --verbose

      - name: Run clippy on zenu-macro
        run: cd zenu-macro && cargo clippy --verbose

      - name: Run clippy on zenu
        run: cd zenu && cargo clippy --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run fmt
        run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests on zenu-matrix
        run: cd zenu-matrix && cargo test --verbose
          
      - name: Run tests on zenu-autograd
        run: cd zenu-autograd && cargo test --verbose

      - name: Run tests on zenu-layer
        run: cd zenu-layer && cargo test --verbose

      - name: Run tests on zenu-optimizer
        run: cd zenu-optimizer && cargo test --verbose

      - name: Run tests on zenu-macro
        run: cd zenu-macro && cargo test --verbose

      - name: Run tests on zenu
        run: cd zenu && cargo test --verbose
