name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: fmt
      run: cargo fmt --verbose
    - name: clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
